import { deepPurple } from "@mui/material/colors";
import { red } from "@mui/material/colors";
import { blue } from "@mui/material/colors";
import { green } from "@mui/material/colors";
import { blueGrey } from "@mui/material/colors";
import { cyan } from "@mui/material/colors";
import { lightBlue } from "@mui/material/colors";
import { purple } from "@mui/material/colors";
import { teal } from "@mui/material/colors";
import { pink } from "@mui/material/colors";
import { orange } from "@mui/material/colors";
import { deepOrange } from "@mui/material/colors";
import { yellow } from "@mui/material/colors";
import { brown } from "@mui/material/colors";
import { amber } from "@mui/material/colors";
import { grey } from "@mui/material/colors";
const colors: any =
    [
        { id: 'pink["A200"]', value: pink["A200"] },
        { id: 'pink["A400"]', value: pink["A400"] },
        { id: 'pink["A700"]', value: pink["A700"] },
        { id: 'amber["A200"]', value: amber["A200"] },
        { id: 'amber["A400"]', value: amber["A400"] },
        { id: 'amber["A700"]', value: amber["A700"] },
        { id: 'blue["A200"]', value: blue["A200"] },
        { id: 'blue["A400"]', value: blue["A400"] },
        { id: 'blue["A700"]', value: blue["A700"] },
        { id: 'blueGrey["300"]', value: blueGrey["300"] },
        { id: 'blueGrey["400"]', value: blueGrey["400"] },
        { id: 'blueGrey["500"]', value: blueGrey["500"] },
        { id: 'brown["700"]', value: brown["700"] },
        { id: 'brown["800"]', value: brown["800"] },
        { id: 'brown["900"]', value: brown["900"] },
        { id: 'cyan["A200"]', value: cyan["A200"] },
        { id: 'cyan["A400"]', value: cyan["A400"] },
        { id: 'cyan["A700"]', value: cyan["A700"] },
        { id: 'deepOrange["A200"]', value: deepOrange["A200"] },
        { id: 'deepOrange["A400"]', value: deepOrange["A400"] },
        { id: 'deepOrange["A700"]', value: deepOrange["A700"] },
        { id: 'deepPurple["A200"]', value: deepPurple["A200"] },
        { id: 'deepPurple["A400"]', value: deepPurple["A400"] },
        { id: 'deepPurple["A700"]', value: deepPurple["A700"] },
        { id: 'green["A200"]', value: green["A200"] },
        { id: 'green["A400"]', value: green["A400"] },
        { id: 'green["A700"]', value: green["A400"] },
        { id: 'lightBlue["A200"]', value: lightBlue["A200"] },
        { id: 'lightBlue["A400"]', value: lightBlue["A400"] },
        { id: 'lightBlue["A700"]', value: lightBlue["A700"] },
        { id: 'orange["A400"]', value: orange["A400"] },
        { id: 'orange["A400"]', value: orange["A400"] },
        { id: 'orange["A700"]', value: orange["A700"] },
        { id: 'purple["A200"]', value: purple["A200"] },
        { id: 'purple["A400"]', value: purple["A400"] },
        { id: 'purple["A700"]', value: purple["A700"] },
        { id: 'red["A200"]', value: red["A200"] },
        { id: 'red["A400"]', value: red["A400"] },
        { id: 'red["A700"]', value: red["A700"] },
        { id: 'teal["A200"]', value: teal["A200"] },
        { id: 'teal["A400"]', value: teal["A400"] },
        { id: 'teal["A700"]', value: teal["A700"] }
    ]

export default colors;